### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by stof** [Stampie/Stampie#59]
There is a 1.0-alpha release replacing the adapter system by HTTPlug.

Is there any roadmap for the remaining work for the 1.0 release ?

**Comment by henrikbjorn** [comment]
There is an alpha2 now, lets just release 1.0.0 when you feel it is ready. It is no secret that i do not use much of php, symfony anymore sadly.

**Comment by Nyholm** [comment]
Im happy with a release of 1.0.0 after: 

* https://github.com/Stampie/Stampie/milestone/1
* I will do some manual testing for each provider.

**Comment by fbourigault** [comment]
The Mandrill Mailer is working (I just tested the API, the email is displayed in the admin. I didn't tested the delivrey).

**Comment by Nyholm** [comment]
(a year later) IMHO we should consider #83 and #88. 

With our without those PRs, we should do something that ease integration testing. After that Im real happy to do 1.0.0

**Comment by fbourigault** [comment]
What about releasing a beta2?

**Comment by stof** [comment]
Closing, as 1.0 has been released.
