### ISSUE TITLE
[Suggestion] change the composer vendor name to stampie

### ISSUE THREAD

**Issue by stof** [Stampie/Stampie#62]
Currently, packages are in the ``henrikbjorn``.

I suggest renaming them to be in the ``stampie`` namespace now that we are in a Github organization. This will make packages easier to manage on Packagist, as we can then give access to all organization maintainers to this namespace (by giving them access to a stampie package).

If we do it, we should do it before the 1.0 release.

**Comment by henrikbjorn** [comment]
Will it have any impact on the packages already published? Also should we mark the packages as replacements for the "old" name?

**Comment by stof** [comment]
yeah, we should mark the package as replacing the old name. And we should keep the old package name on Packagist,, but abandon it.
I can work on this renaming if you want

**Comment by henrikbjorn** [comment]
If you have the time for it, then it would be great :)
