### ISSUE TITLE
Unable to install the package with composer

### ISSUE THREAD

**Issue by zspine** [Stampie/Stampie#79]
I am getting the following error while trying to install stampie 'dev-master' version
```
stampie/stampie dev-master requires php-http/client-implementation ^1.0 -> no matching package found
```

I tried the last stable version and getting the following error, it seems not compatible with the latest guzzle library 
```
Stampie\Adapter\Guzzle::__construct() must be an instance of Guzzle\Http\ClientInterface, instance of GuzzleHttp\Client given
```

Symfony version: 3.3.4

**Comment by stof** [comment]
The GuzzleAdapter in version 0.x is for Guzzle 3, not for Guzzle 4 or 5.

For dev-master (upcoming 1.0), we use HTTPlug. So you need to choose an implementation of the HTTPlug client (I suggest you to use their Guzzle 5 or their Guzzle 6 adapter).
Note that the bundle is not yet updated for 1.0

**Comment by Nyholm** [comment]
Thank you. I added #80 

Basically, you should require a HTTP client as well. See http://docs.php-http.org/en/latest/httplug/users.html

`composer require stampie/stampie:dev-master php-http/guzzle6-adapter php-http/message`

**Comment by zspine** [comment]
@stof @Nyholm Thanks a lot for the detailed instructions and quick response! It works now!
