### ISSUE TITLE
Mandrill subaccounts

### ISSUE THREAD

**Issue by fbourigault** [Stampie/Stampie#92]
> With subaccounts you can separate reputation, activity, reports, and quotas for different types of senders in a single Mandrill account.

Technically subaccounts is specified in the request body. SendGrid has something similar called subUsers but it looks like it works with a different API Key.

How can we support Mandrill subaccounts in Stampie?

**Comment by stof** [comment]
What is your use case ? Having a single subaccount used for your project (i.e. being able to configure the subaccount through DI), or having different messages being sent with different subaccounts ?

The first use case could be solved by allowing to inject a subaccount identifier in the Mandrill mailer constructor.

The second case would require to have something stored in the Message, and so adding this feature to the Stampie abstraction (and then figuring out how this could map to other mailers)

**Comment by fbourigault** [comment]
I need a subaccount for the whole application, but with #93 it became an implementation detail.
