### ISSUE TITLE
[BC break] Simplify the MailerInterface

### ISSUE THREAD

**Issue by stof** [Stampie/Stampie#93]
> @Stampie/collaborators this discussion is about a BC breaking change, so a decision has to be taken before releasing the 1.0 version. If no decision is taken, the release itself will force the decision to be `no` (at least until 2.0).

The current MailerInterface looks like this: https://github.com/Stampie/Stampie/blob/293be7036b977be7fbb15e2fcf2140255de2b0c7/lib/MailerInterface.php#L12-L35

I suggest to simplify it to this:

```php
interface MailerInterface
{
    /**
     * @param MessageInterface $message
     *
     * @throws Exception on failure
     */
    public function send(MessageInterface $message): void;
}
```

Here are my reasoning for the different changes:

- forcing the usage of a server token makes it harder to implement things. Each adapter has a different meaning for it (being an API key, a username+password, etc...), meaning that using the getter and setter requires checking the implementation being used anyway (and so the fact that the methods are in the interface is useless). I think the authentication should be an implementation detail of the Mailer: each mailer would be free to take one or multiple parameters for the auth (allowing to split the username and password for instance, which might make it easier to use env variables for instance), and also to decide whether the auth credentials should be mutable and exposed to consuming code (IMO, they should not)
- the fact that the mailer uses a HTTPlug client should be an implementation detail as well (for instance, in Stampie extra, it does not use a HTTP client, but another Stampie mailer, for which it can fortunately forward the setter, but this is weird), and I see no reason to make it mutable either (so it should be a constructor argument)
- instantiating a new mailer currently creates a broken object (as mandatory dependencies are not passed in the constructor)
- the configuration API of mailers is already wider than the MailerInterface (they all have a `setMessageFactory` setter for instance)
- returning a boolean from `send` makes debugging harder because you don't have an explanation on failure. And in practice, our own implementations are already all throwing exceptions on failures instead of returning true. So our signature is already `@return true  @throws ApiException @throws HttpException` in practice. Returning `true` and never `false` looks weird. Even if we reject the change from `@return true` to `@return void` (with or without return type depending on PHP support), we should at least update the interface to document our actual contract.

what do you think @Stampie/collaborators ?

**Comment by fbourigault** [comment]
I’m 200% ok with this. This will make the library more SOLID.

**Comment by henrikbjorn** [comment]
Simpler is better. Go for it :)
man. 20. nov. 2017 kl. 19.07 skrev Fabien Bourigault <
notifications@github.com>:

**Comment by fbourigault** [comment]
If @Nyholm also agrees, I could take this one as it has to be done before I continue working on the Bundle.

**Comment by Nyholm** [comment]
Awesome 👍

**Comment by fbourigault** [comment]
We are unanimous about this new `MailerInterface`. @stof can I take it?

**Comment by stof** [comment]
yes you can.

Note that to make the upgrade simpler, I would still keep the setters in the implementation for now. But as they would not be part of the interface anymore, they would be an implementation detail. And we can then improve the auth configuration later (can be post-1.0 by using a deprecation).
