### ISSUE TITLE
Rewrite tests to avoid using partial mocks

### ISSUE THREAD

**Issue by stof** [Stampie/Stampie#96]
Currently, the mailer tests are using partial mocks of the mailers to replace a protected method getting the attachment content.

We should rewrite tests to use an actual fixture file instead, which would allow to remove the protected extension point from these mailers.

**Comment by fbourigault** [comment]
Could you point out which kind of tests you want to be rewrited?

**Comment by stof** [comment]
Currently, all mailer tests are using partial mocks of the mailers.

The main reason is to mock the protected method getting the content of the attachment (which has no reason to even exist as a protected method, except for this mocking).
These tests should instead use an actual file (stored in a `Fixtures` folder in tests) and use the mailer without mocking it.
